name: age_gender_prediction
description: Prediction

publish_to: 'none'
version: 1.0.1+3

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  superellipse_shape: ^0.2.0
  flutter_bloc: ^8.0.0
  google_fonts: ^2.1.0
  crypto: 3.0.1

  google_mobile_ads: ^1.0.1

  firebase_core: ^1.10.6
  firebase_storage: ^10.2.4
  firebase_analytics: ^9.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.3.2

flutter:
  uses-material-design: true
