name: age_gender_prediction
description: Prediction

publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  image_picker: 0.7.4
  firebase_core: 1.0.3
  firebase_storage: 8.0.3
  uuid: 3.0.4
  superellipse_shape: ^0.1.6
  facebook_audience_network: ^0.9.0
  flutter_bloc: ^7.0.0
  google_fonts: ^2.0.0
  crypto: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
