name: age_gender_prediction
description: Prediction

publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+11
  superellipse_shape: ^0.2.0
  flutter_bloc: ^8.0.1
  google_fonts: ^2.3.1
  crypto: 3.0.1

  google_mobile_ads: ^1.1.0

  firebase_core: ^1.13.1
  firebase_storage: ^10.2.9
  firebase_analytics: ^9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.1.1

flutter:
  uses-material-design: true