name: age_gender_prediction
description: Prediction

publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.6
  superellipse_shape: ^0.2.0
  flutter_bloc: ^8.1.1
  google_fonts: ^3.0.1
  crypto: ^3.0.2

  google_mobile_ads: ^2.3.0

  tflite: ^1.1.2

  firebase_core: ^2.4.0
  firebase_storage: ^11.0.8
  firebase_analytics: ^10.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.16

flutter:
  uses-material-design: true
  assets:
    - assets/model.tflite
    - assets/labels.txt